name = "advent-of-ai-security-website"
main = "./dist/_worker.js"
compatibility_date = "2025-10-11"

routes = [
  { pattern = "advent-of-ai-security.com", custom_domain = true }
]

[assets]
directory = "./dist"
binding = "ASSETS"

